name: bias_correction
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # - python==3.10.12
  - pytorch-lightning==2.2.1
  - numba
  - dask==2024.3.1
  - xesmf==0.8.4
  - zarr==2.17.1
  - geopandas==0.14.3
  - fiona==1.9.6
  - geopy==2.4.1
  - netcdf4==1.6.5
  - rasterio==1.3.9
  - hydra-core==1.3.2
  - omegaconf==2.3.0
  - matplotlib==3.8.3
  - scikit-learn==1.4.1.post1
  - flake8==7.0.0
  - ipywidgets==8.1.2
  - polars==0.20.16
  - swifter==1.4.0
  - pyarrow
  - gcsfs==2024.3.1
  - esgf-pyclient==0.3.1
  - cartopy==0.22.0
  - catboost==1.2.3
  - transformers==4.38.2
  - fastparquet==2024.2.0
  - torchdata==0.7.1
  - ipykernel==6.29.3
  - diffusers
  - rioxarray==0.15.1
  - ipyleaflet==0.18.2
  - pip
  - pip:
    - wandb==0.16.4
    - climate-learn==1.0.0
    - optuna==3.6.0
    - opencv-python==4.9.0.80
    - einops==0.7.0
    - rich==13.7.1
    - nvitop==0.2.5.1
    - pytorch-msssim
    - hydroeval
