---
experiment_name: unit_test
data_dir: 'data/dummy_test'
path_to_prepared_target_data: 'data/dummy_test/target.parquet'
precision: 16
normalize: False
time_window: 3
half_side_size: 3
start_of_test: 1917
variables:
- 'var_1'
- 'var_2'
- 'var_3'
- 'var_4'
- 'var_5'
- 'var_6'
start_date: '1890-12-02'
number_of_days: 7334 # 365 * 20 + 30
