from .climatology import Climatology
from .interpolation import Interpolation
from .unet_upsampling import UnetUpsampling
from .linear_regression import LinearRegression
from .persistence import Persistence
from .resnet import ResNet
from .unet import Unet
from .utils import MODEL_REGISTRY
from .vit import VisionTransformer
from .diffusion import GaussianDiffusion
from .samvit import VisionTransformerSAM
from .ynet import YNet30
from .deepsd import DeepSD
from .gan import DCGAN
from .edrn import EDRN
from .esr_gan import ESRGAN
from .hat import HAT