from .climatology import Climatology
from .interpolation import Interpolation
from .unet_upsampling import UnetUpsampling
from .linear_regression import LinearRegression
from .persistence import Persistence
from .resnet import ResNet
from .unet import Unet
from .utils import MODEL_REGISTRY
from .vit import VisionTransformer
from .samvit import VisionTransformerSAM
