defaults:
  - raw: cmip6_1deg_paths    # paths to raw data to prepare dataset
  - process: cmip6_dataset_temp        # dataset processing configuration
  - train: train_cmip6_wind     # train configuration and data load configuration
  - eval: GhostWindNet_wind
  - visual: eobs_cmip.yaml

experiment_name: cmip6_GhostWindNet47x27_wind
project_name: Wind-speed-regression
target_type: wind_ms #*
cmip_type: CMIP6 #*

model_name: GhostWindNet27  # {name}{time_window}x{half_side_size}
time_window: 27               # must match model, odd only
half_side_size: 47            # must match model, odd only

start_date: '2000-06-01'                   #for eval only
end_date: '2022-07-01'
