defaults:
  - raw: cmip5_paths                               # paths to raw data to prepare dataset
  - process: cmip5_dataset                         # dataset processing configuration
  - train: train_cmip5_test_run  # train configuration and data load configuration
  - eval: test_GhostWindNet                        # test and eval configuration 

experiment_name: cmip5_reg_GhostWindNet27x47
project_name: Wind-speed-regression
target_type: temp_c 
cmip_type: CMIP6 

model_name: GhostWindNet27      # {name}{time_window}x{half_side_size}
time_window: 27               # must match model, odd only
half_side_size: 47            # must match model, odd only

start_date: '2019-03-30'                   #for eval only
end_date: '2019-03-31'