defaults:
  - raw: cmip6_elevation_paths    # paths to raw data to prepare dataset
  - process: cmip6_dataset        # dataset processing configuration
  - train: train_cmip6_temp     # train configuration and data load configuration
  - eval: test_baseline

experiment_name: cmip6_baseline_temp_q
project_name: Wind-speed-regression
target_type: temp_c #*
cmip_type: CMIP6 #*

model_name: BaselineQT  # {name}{time_window}x{half_side_size}
time_window: 27               # must match model, odd only
half_side_size: 1            # must match model, odd only

start_date: '2018-06-06'                   #for eval only
end_date: '2018-06-07'
