save_path: '/app/data/raw/'
local_path: 'era5_0.25_D'
task: 'era5-eobs' # "era5-eobs" | "cmip6-era5" 

year_start: 1960
year_end: 2014

constants:
    - "land_sea_mask"
    - "geopotential_at_surface"

eobs_bounds:
    left: -15
    right: 40
    top: 71
    bottom: 35

# isobaric surfaces
# level:
#     - 50
#     - 200
#     - 250
#     - 300
#     - 500
#     - 700
#     - 850
#     - 925
#     - 1000