era_save_path: '/app/data/era5'

year_start: 1980
year_end: 2010

# variables
single_level_vars:
    - "2m_temperature"
    - "total_precipitation"
# multilevel_vars:
#     - "geopotential"

# isobaric surfaces
level:
    - 50
    - 200
    - 250
    - 300
    - 500
    - 700
    - 850
    - 925
    - 1000