model_name: WindNet27x47 # have no effect
make_tmp_target_file: False

use_elevation: false
normalize: false      # precision 16 is already normalized
time_agg_window: 28   # range in days, used to calculate maximum for every day of target
time_freq: 14         # get sample from target every {time_freq} days
target_threshold: 3

data_dir: data/cmip5_world3/      # directory to get climate files for training
target_data_file: target_pr.parquet  # target data file in data_dir for training
       
start_time: '2006-02-02'
end_time: '2010-02-02'
start_of_test: '2008-03-03'

spatial_crop: true
lat_min: 30
lat_max: 50
lon_min: -30
lon_max: 40

batch_size: 15
learning_rate: 0.009
weight_decay: 0.0001
max_epoch: 2

optimizer_name: 'AdamW'
scheduler_name: 'LinearLR'
loss_name: 'MSELoss'

num_workers: 8
gpu_num: 1
distributed: false
num_nodes: 1
strategy: 'ddp'

log_every_n_steps: 100 