data_dir: /app/wind/data/01-prepared/cmip6_1deg_world                      #Path to folder which will contain prepocessed data for further training, testing and inferring 
prepared_target_data_name: target_dew.parquet       #Prepared target will be saved under this name

make_climate_data: false                         #If to prepare climate data. Turn to `false` if you already done this step and do not want to change anything regarding climate data
make_elevation_data: false                       #If to prepare elevation data. Turn to `false` if you already done this step and do not want to change anything regarding elevation data
make_normalization: false                        #If to make normalization for climate and elevation. !Pay attention to saved_normalized and precision!
make_cleaned_weather_data: true                 #If to pre-prepare target data cleaning - data types
make_target: true                               #If to assemble target data. Turn `false` this and `make_cleaned_weather_data` if you do not want to change anything regarding target data

load_normalization: false                        #!Recommended to set True!If to load pre-computed means and stds for variables

saved_normalized: true                          #Only save to float16 with saved_normalized=true 
precision: 16 # 32                              #Floating precision

spatial_crop: False                             #Recommended to use `False`. If to crop climate data
coords:                                         #Crop coordinates
  lat_min: -89.0
  lat_max: 89.0
  lon_min: -179.5
  lon_max: 180.45
  
min_height: -10                                 #Weather station min height to be used
max_height: 800                                 #Weather station max height to be used

variables:                                      #CMIP variable names to use
- sfcWindmax
- tasmax
- tasmin

time_limits:                                    #Time limits for target and climate data
- '1950-01-01'
- '2023-01-01'
start_of_test: '2008-01-01'                     #Train-test temporal separation

target_column:                                  #Target variable columns from weather stations 
# - 'max_speed'
# - 'avg_speed'
# - 'avg_temp'
# - 'sea_level_pressure'
# - 'station_level_pressure'
# - 'precipitation'
- 'dew_point_temp'